### ISSUE TITLE
Bug : Export to CSV of the current collection does not work (right click from the result table)

### ISSUE THREAD

**Issue by dev-mansonthomas** [thanhlmm/refi-app#63]
Hello There,

The export as CSV feature, when right clicking on the result table does not work.
Nothing happen after the click.

In my use case, I was filtering the collection on a field (id=(number)7483). I would have expected to export the collection filtered.

I was able to export the full collection from the left pane, but not filtered. 

<img width="423" alt="image" src="https://user-images.githubusercontent.com/5695269/167705075-5793bb7b-a98d-4367-87cc-81483c42b289.png">

**Comment by ttyniwa** [comment]
me too.
also below commands does not work.

Export document as JSON
Export current table as CSV
Export current table as JSON

**Comment by thanhlmm** [comment]
Hey guys, thanks for reporting it. I will fix ASAP

**Comment by thanhlmm** [comment]
@dev-mansonthomas @ttyniwa 

Hi thanks for reporting, the issue has been fixed in the latest version. Check it out: https://github.com/thanhlmm/refi-app/releases/tag/v0.0.16

**Comment by ttyniwa** [comment]
@thanhlmm 

thank you for your quick work.
I updated, but still reproduce.

**Comment by thanhlmm** [comment]
Hi @ttyniwa , can you confirm that you're using v0.0.16 by clicking on the menu and select About

<img width="333" alt="image" src="https://user-images.githubusercontent.com/9281080/168423334-5d363d08-b3b6-46a4-b5bd-61d99a579772.png">

**Comment by thanhlmm** [comment]
Oh it have some issue regarding to release process, please stay tuned, I will try to solve it

**Comment by PaulBouisset** [comment]
Hi @thanhlmm it seem that the export issue is still there, both in version 0.0.16 and 0.0.17 😬
